POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "other.email@hotmail.com",
  "password": "Password",
  "admin": true
}

###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "other.email@hotmail.com",
  "password": "Password"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=email@hotmail.com

### Delete a user a given ID
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "myEmail@gmail.com"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout
